import type { Listing } from './types';

/**
 * Curated demo stays for the judge path — always labeled in UI.
 * Live OpenStreetMap / Wheelmap places merge in via enrichment (provenance: open-data).
 * IDs and accessibility keys align with `api/router.mjs` MOCK_PROPERTIES.
 */
export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'prop-001',
    name: 'Harborview Accessible Hotel',
    location: 'New York, NY',
    address: '120 West 45th Street, New York, NY 10036',
    city: 'New York',
    state: 'NY',
    category: 'hotel',
    price: 189,
    priceLabel: 'per night',
    rating: 4.8,
    reviewCount: 142,
    verified: true,
    provenance: 'curated-demo',
    // On-chain badge only after a real Monad tx (wallet or server) — never a fake hash.
    verifiedOnChain: false,
    summary:
      'Downtown hotel with verified roll-in shower rooms, 36-inch doorways, and staffed accessibility desk at check-in.',
    description:
      'Harborview offers dedicated accessible king rooms with roll-in showers, grab bars, and lowered closet rods.',
    coordinates: { lat: 40.7569, lng: -73.9845 },
    photos: [],
    accessibility: {
      wheelchairRamp: true,
      rollInShower: true,
      elevator: true,
      wideDoorways: true,
      accessibleParking: true,
      accessibleRestroom: true,
      accessibleEntrance: true,
      loweredBathroom: true,
      serviceAnimalsAllowed: true,
    },
  },
  {
    id: 'prop-002',
    name: 'Lincoln Park Inclusive Stay',
    location: 'Chicago, IL',
    city: 'Chicago',
    state: 'IL',
    category: 'airbnb',
    price: 129,
    priceLabel: 'per night',
    rating: 4.5,
    reviewCount: 87,
    verified: true,
    provenance: 'curated-demo',
    summary:
      'Ground-floor stay with ramp entry and wide hallway. Roll-in shower reported by 12 community reviewers.',
    accessibility: {
      wheelchairRamp: true,
      rollInShower: true,
      elevator: false,
      wideDoorways: true,
      accessibleParking: true,
      accessibleRestroom: true,
      accessibleEntrance: true,
      loweredBathroom: true,
      serviceAnimalsAllowed: true,
    },
  },
  {
    id: 'prop-003',
    name: 'SFO Accessibility Services Hub',
    location: 'San Francisco, CA',
    city: 'San Francisco',
    state: 'CA',
    category: 'airport',
    price: 0,
    priceLabel: 'public facility',
    rating: 4.2,
    reviewCount: 54,
    verified: true,
    provenance: 'curated-demo',
    summary:
      'Terminal accessibility desk, elevator maps, and wheelchair assistance between gates.',
    accessibility: {
      wheelchairRamp: true,
      rollInShower: false,
      elevator: true,
      wideDoorways: true,
      accessibleParking: true,
      accessibleRestroom: true,
      accessibleEntrance: true,
      loweredBathroom: true,
      serviceAnimalsAllowed: true,
    },
  },
  {
    id: 'prop-004',
    name: 'Ocean Breeze Accessible Resort',
    location: 'Miami, FL',
    city: 'Miami',
    state: 'FL',
    category: 'hotel',
    price: 249,
    priceLabel: 'per night',
    rating: 4.7,
    reviewCount: 210,
    verified: true,
    provenance: 'curated-demo',
    summary:
      'Beachfront property with pool lift, accessible paths, and multiple roll-in shower suites.',
    accessibility: {
      wheelchairRamp: true,
      rollInShower: true,
      elevator: true,
      wideDoorways: true,
      accessibleParking: true,
      accessibleRestroom: true,
      accessibleEntrance: true,
      loweredBathroom: true,
      serviceAnimalsAllowed: true,
    },
  },
  {
    id: 'prop-005',
    name: 'Sunshine Family Suites Orlando',
    location: 'Orlando, FL',
    city: 'Orlando',
    state: 'FL',
    category: 'hotel',
    price: 165,
    priceLabel: 'per night',
    rating: 4.6,
    reviewCount: 98,
    verified: true,
    provenance: 'curated-demo',
    summary:
      'Theme-park area hotel popular with families — roll-in showers, pool ramp, and wide suite doorways.',
    accessibility: {
      wheelchairRamp: true,
      rollInShower: true,
      elevator: true,
      wideDoorways: true,
      accessibleParking: true,
      accessibleRestroom: true,
      accessibleEntrance: true,
      loweredBathroom: true,
      serviceAnimalsAllowed: true,
    },
  },
  {
    id: 'prop-006',
    name: 'Brooklyn Heights Accessible Loft',
    location: 'New York, NY',
    city: 'New York',
    state: 'NY',
    category: 'airbnb',
    price: 175,
    priceLabel: 'per night',
    rating: 4.4,
    reviewCount: 63,
    verified: true,
    provenance: 'curated-demo',
    summary:
      'Elevator building with 34-inch doorway and tub transfer bench available on request — no roll-in shower.',
    accessibility: {
      wheelchairRamp: true,
      rollInShower: false,
      elevator: true,
      wideDoorways: true,
      accessibleParking: false,
      accessibleRestroom: true,
      accessibleEntrance: true,
      loweredBathroom: false,
      serviceAnimalsAllowed: true,
    },
  },
  {
    id: 'prop-007',
    name: 'MCO Terminal B Mobility Center',
    location: 'Orlando, FL',
    city: 'Orlando',
    state: 'FL',
    category: 'airport',
    price: 0,
    priceLabel: 'public facility',
    rating: 4.3,
    reviewCount: 41,
    verified: true,
    provenance: 'curated-demo',
    summary:
      'Orlando International — wheelchair service, accessible restrooms, and elevator access to all concourses.',
    accessibility: {
      wheelchairRamp: true,
      rollInShower: false,
      elevator: true,
      wideDoorways: true,
      accessibleParking: true,
      accessibleRestroom: true,
      accessibleEntrance: true,
      loweredBathroom: true,
      serviceAnimalsAllowed: true,
    },
  },
];

export function getListingById(id: string): Listing | undefined {
  return MOCK_LISTINGS.find((l) => l.id === id);
}
